export const PLAYER_ACTION_TYPE = {
    CHANGE_CURRENT_SONG: "player/CHANGE_CURRENT_SONG",
    CHANGE_PLAY_LIST: "player/CHANGE_PLAY_LIST",
    CHANGE_CURRENT_SONG_INDEX: "player/CHANGE_CURRENT_SONG_INDEX",
    CHANGE_SEQUENCE: "player/CHANGE_SEQUENCE",
};