export const RECOMMEND_ACTION_TYPE = {
    CHANGE_TOP_BANNERS: 'recommend/CHANGE_TOP_BANNERS',
    CHANGE_HOT_RECOMMEND: 'recommend/CHANGE_HOT_RECOMMEND',
    CHANGE_NEW_ALBUMS: 'recommend/CHANGE_NEW_ALBUMS',
    CHANGE_UP_RANKING: 'recommend/CHANGE_UP_RANKING',
    CHANGE_NEW_RANKING: 'recommend/CHANGE_NEW_RANKING',
    CHANGE_ORIGINAL_RANKING: 'recommend/CHANGE_ORIGINAL_RANKING',
}