export const RECOMMEND_ACTION_TYPE = {
    CHANGE_TOP_BANNERS: 'recommend/CHANGE_TOP_BANNERS',
    CHANGE_HOT_RECOMMEND: 'recommend/CHANGE_HOT_RECOMMEND',
    CHANGE_NEW_ALBUMS: 'recommend/CHANGE_NEW_ALBUMS',
}